### ISSUE TITLE
Tourist route planner JavaScript error

### ISSUE THREAD

**Issue by dsyer** [spansh/elite-dangerous-issues#10]
Adding a destination fails for me:

```
tourist.js:73 Uncaught TypeError: this.destinations.arrayContentDidChange is not a function
    at s.changeDestination (tourist.js:73:1)
    at Proxy.<anonymous> (runtime.js:5568:1)
    at c.onchange (autocomplete-search.js:129:1)
    at h._select (power-select.js:577:1)
    at h._choose (power-select.js:582:1)
    at r (options.js:111:1)
    at HTMLUListElement.mouseUpHandler (options.js:113:1)
```

**Comment by spansh** [comment]
Thanks for the report, this should now be fixed
